CREATE TABLE INVENTORY_RECORDS_DATA (
    PRODUCT_ID VARCHAR(6) UNIQUE PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    OPENING_STOCK INT,
    PURCHASE_STOCK_IN INT,
    N_UNITS_SOLD INT,
    HAND_IN_STOCK INT,
    COST_PER_UNIT MONEY,
    COST_PRICE_TOTAL MONEY
);